### ISSUE TITLE
Include TypeScript types in this repo

### ISSUE THREAD

**Issue by osdiab** [sindresorhus/is-relative-url#3]
Already on `DefinitelyTyped`, but would be nice to just drop them in here since it's so simple.

**Comment by sindresorhus** [comment]
// @BendingBender

**Comment by osdiab** [comment]
Also would love not having to enable `allowSyntheticDefaultImports` just for this library, but guess that might require a change in the API, so probably not worth it.

**Comment by BendingBender** [comment]
@osdiab I know, it just takes time. We're open for pull requests.

**Comment by BendingBender** [comment]
Regarding `allowSyntheticDefaultImports`, you can switch to the much safer flag `esModuleInterop`. This won't change, even after moving here you'll need to use one of the mentioned flags.

**Comment by osdiab** [comment]
I decided that this library is so simple it's safer for me to just have the equivalent code in my own repository (with attribution) rather than having the external dep, so I'll pass for now on this - just thought I'd log it at least for posterity.
