### ISSUE TITLE
Can you please explain what is the main use of this package?

### ISSUE THREAD

**Issue by nandhahacker1** [sindresorhus/is-relative-url#8]
### Can you please explain what is the main use of this package?

- This package weekly download = **13,957,734**.
- It's give **true** if match URL else **false**.

What is the reason for popularity. I mean the Use of it. what can I do using this package?

**Comment by sindresorhus** [comment]
It's popular because some popular packages depend on it. If you don't see the use-case for it, you probably don't need it.
